---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: golang
    commands:
      - go test ./...

---
kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
  - name: test
    image: golang
    commands:
      - go test ./...
